[project]
name = "sensor-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-circuitpython-dht>=4.0.8",
    "pika>=1.3.2",
    "pytest>=8.3.5",
    "python-dotenv>=1.1.0",
    # "rpi-gpio>=0.7.1",

]

